SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE DATABASE IF NOT EXISTS DEV_4TP_DB DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;;
USE DEV_4TP_DB;

CREATE TABLE IF NOT EXISTS `TB_USUARIO` (
	CD_USUARIO INT NOT NULL AUTO_INCREMENT,
	NM_USUARIO VARCHAR(60) NOT NULL,
	IM_USUARIO TEXT NULL,
	NM_EMAIL_USUARIO VARCHAR(255) NOT NULL,
	CD_SENHA_USUARIO TEXT NOT NULL,
	PRIMARY KEY (`CD_USUARIO`)
);

CREATE TABLE IF NOT EXISTS `TB_ENDERECO_USUARIO` (
	CD_ENDERECO_USUARIO INT(11) NOT NULL AUTO_INCREMENT,
	NM_RUA_ENDERECO_USUARIO VARCHAR(255) NOT NULL,
	DS_COMPLEMENTO_ENDERECO_USUARIO TEXT NULL,
	NM_BAIRRO_ENDERECO_USUARIO VARCHAR(255) NOT NULL,
	CIDADE_ENDERECO_USUARIO VARCHAR(45) NOT NULL,
	SG_UNIDADE_FEDERATIVA_ENDERECO_USUARIO VARCHAR(2) NOT NULL,
	FK_USUARIO INT(11) NULL,
	PRIMARY KEY (`CD_ENDERECO_USUARIO`),
	KEY `FK_USUARIO` (`FK_USUARIO`)
);

CREATE TABLE IF NOT EXISTS `TB_PET_ADICIONADO_ADOCAO_USUARIO` (
	CD_PET_ADICIONADO_ADOCAO_USUARIO INT(11) NOT NULL AUTO_INCREMENT,
	NM_PET_ADICIONADO_ADOCAO_USUARIO VARCHAR(255) NOT NULL,
	NM_CATEGORIA_PET_ADICIONADO_ADOCAO_USUARIO VARCHAR(20) NOT NULL,
	IC_SEXO_PET_ADICIONADO_ADOCAO_USUARIO CHAR(1) NOT NULL,
	NR_IDADE_PET_ADICIONADO_ADOCAO_USUARIO INT(2) NOT NULL,
	BOOL_CASTRACAO_PET_ADICIONADO_ADOCAO_USUARIO BOOLEAN NULL,
	IM_PET_ADICIONADO_ADOCAO_USUARIO TEXT NULL,
	FK_USUARIO INT(11),
	PRIMARY KEY (`CD_PET_ADICIONADO_ADOCAO_USUARIO`),
	KEY `FK_USUARIO` (`FK_USUARIO`)
);

CREATE TABLE IF NOT EXISTS `TB_PET_INTERESSE_ADOCAO_USUARIO` (
	CD_PET_INTERESSE_ADOCAO_USUARIO INT(11) NOT NULL AUTO_INCREMENT,
	FK_USUARIO INT(11),
	FK_PET_ADICIONADO_ADOCAO_USUARIO INT(11),
	PRIMARY KEY (`CD_PET_INTERESSE_ADOCAO_USUARIO`),
	KEY `FK_USUARIO` (`FK_USUARIO`),
	KEY `FK_PET_ADICIONADO_ADOCAO_USUARIO` (`FK_PET_ADICIONADO_ADOCAO_USUARIO`)
);

CREATE TABLE IF NOT EXISTS `TB_DENUNCIA_USUARIO` (
	CD_DENUNCIA_USUARIO INT(11) NOT NULL AUTO_INCREMENT,
	NM_MOTIVO_DENUNCIA VARCHAR(100) NOT NULL,
	DS_DENUNCIA TEXT NOT NULL,
	FK_USUARIO_GERADOR_DENUNCIA INT(11),
	FK_USUARIO_DENUNCIADO INT(11),
	PRIMARY KEY (`CD_DENUNCIA_USUARIO`),
	KEY `FK_USUARIO_GERADOR_DENUNCIA` (`FK_USUARIO_GERADOR_DENUNCIA`),
	KEY `FK_USUARIO_DENUNCIADO` (`FK_USUARIO_DENUNCIADO`)
);

ALTER TABLE `TB_ENDERECO_USUARIO`
	ADD CONSTRAINT `END_IBFK_00` FOREIGN KEY (`FK_USUARIO`) REFERENCES `TB_USUARIO` (`CD_USUARIO`);

ALTER TABLE `TB_PET_ADICIONADO_ADOCAO_USUARIO`
	ADD CONSTRAINT `PET_AD_IBFK_00` FOREIGN KEY (`FK_USUARIO`) REFERENCES `TB_USUARIO` (`CD_USUARIO`);

ALTER TABLE `TB_PET_INTERESSE_ADOCAO_USUARIO`
	ADD CONSTRAINT `PET_IT_IBFK_00` FOREIGN KEY (`FK_USUARIO`) REFERENCES `TB_USUARIO` (`CD_USUARIO`);

ALTER TABLE `TB_PET_INTERESSE_ADOCAO_USUARIO`
	ADD CONSTRAINT `PET_IT_IBFK_01` FOREIGN KEY (`FK_PET_ADICIONADO_ADOCAO_USUARIO`) REFERENCES `TB_PET_ADICIONADO_ADOCAO_USUARIO` (`CD_PET_ADICIONADO_ADOCAO_USUARIO`);

ALTER TABLE `TB_DENUNCIA_USUARIO`
	ADD CONSTRAINT `DEN_US_IBFK_00` FOREIGN KEY (`FK_USUARIO_GERADOR_DENUNCIA`) REFERENCES `TB_USUARIO` (`CD_USUARIO`);

ALTER TABLE `TB_DENUNCIA_USUARIO`
	ADD CONSTRAINT `DEN_US_IBFK_01` FOREIGN KEY (`FK_USUARIO_DENUNCIADO`) REFERENCES `TB_USUARIO` (`CD_USUARIO`);
