SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE DATABASE IF NOT EXISTS LOCAL_4TP_DB DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;;
USE LOCAL_4TP_DB;

CREATE TABLE IF NOT EXISTS `TB_USUARIO` (
	CODE_USUARIO INT NOT NULL AUTO_INCREMENT,
	NAME_USUARIO VARCHAR(60) NOT NULL,
	IMAG_USUARIO TEXT NULL,
	NAME_EMAIL_USUARIO VARCHAR(255) NOT NULL,
	CODE_SENHA_USUARIO TEXT NOT NULL,
    SYS_DATE_CRIACAO_CONTA_USUARIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SYS_BOOL_NIVEL_PERMISSAO_USUARIO BOOLEAN DEFAULT 0,
    SYS_BOOL_TUTORIAL_COMPLETO BOOLEAN DEFAULT 0,
	PRIMARY KEY (`CODE_USUARIO`)
);

CREATE TABLE IF NOT EXISTS `TB_ENDERECO_USUARIO` (
	CODE_ENDERECO_USUARIO INT(11) NOT NULL AUTO_INCREMENT,
	NAME_RUA_ENDERECO_USUARIO VARCHAR(255) NOT NULL,
	DESC_COMPLEMENTO_ENDERECO_USUARIO TEXT NULL,
	NAME_BAIRRO_ENDERECO_USUARIO VARCHAR(255) NOT NULL,
	CITY_ENDERECO_USUARIO VARCHAR(45) NOT NULL,
	CODE_UNIDADE_FEDERATIVA_ENDERECO_USUARIO VARCHAR(2) NOT NULL,
    CDFK_USUARIO INT(11) NULL,
    SYS_DATE_ATUALIZACAO_ENDERECO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`CODE_ENDERECO_USUARIO`),
	KEY `CDFK_USUARIO` (`CDFK_USUARIO`)
);

CREATE TABLE IF NOT EXISTS `TB_TELEFONE_USUARIO` (
	CODE_TELEFONE_USUARIO INT(11) NOT NULL AUTO_INCREMENT,
	NBR_TELEFONE_USUARIO INT(13) NOT NULL,
	CDFK_USUARIO INT(11),
	SYS_DATE_CRIACAO_TELEFONE_USUARIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`CODE_TELEFONE_USUARIO`),
	KEY `CDFK_USUARIO` (`CDFK_USUARIO`)
);

CREATE TABLE IF NOT EXISTS `TB_PET_ADICIONADO_ADOCAO_USUARIO` (
	CODE_PET_ADICIONADO_ADOCAO_USUARIO INT(11) NOT NULL AUTO_INCREMENT,
	NAME_PET_ADICIONADO_ADOCAO_USUARIO VARCHAR(255) NOT NULL,
	NAME_CATEGORIA_PET_ADICIONADO_ADOCAO_USUARIO VARCHAR(20) NOT NULL,
	GNR_SEXO_PET_ADICIONADO_ADOCAO_USUARIO VARCHAR(5) NOT NULL,
	NBR_IDADE_PET_ADICIONADO_ADOCAO_USUARIO INT(2) NOT NULL,
	BOOL_CASTRACAO_PET_ADICIONADO_ADOCAO_USUARIO BOOLEAN NULL,
	IMAG_PET_ADICIONADO_ADOCAO_USUARIO TEXT NULL,
    CDFK_USUARIO INT(11),
    SYS_DATE_PET_ADICIONADO_ADOCAO_USUARIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	SYS_BOOL_PET_REMOVIDO_ADOCAO_USUARIO BOOLEAN,
	PRIMARY KEY (`CODE_PET_ADICIONADO_ADOCAO_USUARIO`),
	KEY `CDFK_USUARIO` (`CDFK_USUARIO`)
);

CREATE TABLE IF NOT EXISTS `TB_PET_INTERESSE_ADOCAO_USUARIO` (
	CODE_PET_INTERESSE_ADOCAO_USUARIO INT(11) NOT NULL AUTO_INCREMENT,
	CDFK_USUARIO INT(11),
	CDFK_PET_ADICIONADO_ADOCAO_USUARIO INT(11),
    SYS_PET_INTERESSE_ADOCAO_USUARIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`CODE_PET_INTERESSE_ADOCAO_USUARIO`),
	KEY `CDFK_USUARIO` (`CDFK_USUARIO`),
	KEY `CDFK_PET_ADICIONADO_ADOCAO_USUARIO` (`CDFK_PET_ADICIONADO_ADOCAO_USUARIO`)
);

CREATE TABLE IF NOT EXISTS `TB_PET_AMEI_USUARIO` (
    CODE_PET_AMEI_USUARIO INT(11) NOT NULL AUTO_INCREMENT,
    CDFK_PET_ADICIONADO_ADOCAO_USUARIO INT(11),
    CDFK_USUARIO INT(11),
    SYS_DATE_PET_AMEI_USUARIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    SYS_BOOL_PET_AMEI_USUARIO_IS_REMOVED BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY (`CODE_PET_AMEI_USUARIO`),
	KEY `CDFK_USUARIO` (`CDFK_USUARIO`),
	KEY `CDFK_PET_ADICIONADO_ADOCAO_USUARIO` (`CDFK_PET_ADICIONADO_ADOCAO_USUARIO`)
);

CREATE TABLE IF NOT EXISTS `TB_DENUNCIA_USUARIO` (
	CODE_DENUNCIA_USUARIO INT(11) NOT NULL AUTO_INCREMENT,
	NAME_MOTIVO_DENUNCIA VARCHAR(100) NOT NULL,
	DESC_DENUNCIA TEXT NOT NULL,
	CDFK_USUARIO_GERADOR_DENUNCIA INT(11),
	CDFK_USUARIO_DENUNCIADO INT(11),
    SYS_DATE_DENUNCIA_USUARIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`CODE_DENUNCIA_USUARIO`),
	KEY `CDFK_USUARIO_GERADOR_DENUNCIA` (`CDFK_USUARIO_GERADOR_DENUNCIA`),
	KEY `CDFK_USUARIO_DENUNCIADO` (`CDFK_USUARIO_DENUNCIADO`)
);

ALTER TABLE `TB_ENDERECO_USUARIO`
	ADD CONSTRAINT `END_IBFK_00` FOREIGN KEY (`CDFK_USUARIO`) REFERENCES `TB_USUARIO` (`CODE_USUARIO`);

ALTER TABLE `TB_TELEFONE_USUARIO`
	ADD CONSTRAINT `TEL_IBFK_00` FOREIGN KEY (`CDFK_USUARIO`) REFERENCES `TB_USUARIO` (`CODE_USUARIO`);

ALTER TABLE `TB_PET_ADICIONADO_ADOCAO_USUARIO`
	ADD CONSTRAINT `PET_AD_IBFK_00` FOREIGN KEY (`CDFK_USUARIO`) REFERENCES `TB_USUARIO` (`CODE_USUARIO`);

ALTER TABLE `TB_PET_INTERESSE_ADOCAO_USUARIO`
	ADD CONSTRAINT `PET_IT_IBFK_00` FOREIGN KEY (`CDFK_USUARIO`) REFERENCES `TB_USUARIO` (`CODE_USUARIO`);

ALTER TABLE `TB_PET_INTERESSE_ADOCAO_USUARIO`
	ADD CONSTRAINT `PET_IT_IBFK_01` FOREIGN KEY (`CDFK_PET_ADICIONADO_ADOCAO_USUARIO`) REFERENCES `TB_PET_ADICIONADO_ADOCAO_USUARIO` (`CODE_PET_ADICIONADO_ADOCAO_USUARIO`);

ALTER TABLE `TB_DENUNCIA_USUARIO`
	ADD CONSTRAINT `DEN_US_IBFK_00` FOREIGN KEY (`CDFK_USUARIO_GERADOR_DENUNCIA`) REFERENCES `TB_USUARIO` (`CODE_USUARIO`);

ALTER TABLE `TB_DENUNCIA_USUARIO`
	ADD CONSTRAINT `DEN_US_IBFK_01` FOREIGN KEY (`CDFK_USUARIO_DENUNCIADO`) REFERENCES `TB_USUARIO` (`CODE_USUARIO`);

ALTER TABLE `TB_PET_AMEI_USUARIO`
	ADD CONSTRAINT `PET_AM_IBFK_00` FOREIGN KEY (`CDFK_USUARIO`) REFERENCES `TB_USUARIO` (`CODE_USUARIO`);

ALTER TABLE `TB_PET_AMEI_USUARIO`
	ADD CONSTRAINT `PET_AM_IBFK_01` FOREIGN KEY (`CDFK_PET_ADICIONADO_ADOCAO_USUARIO`) REFERENCES `TB_PET_ADICIONADO_ADOCAO_USUARIO` (`CODE_PET_ADICIONADO_ADOCAO_USUARIO`);
